### PR TITLE
Add javadoc for vision and parameter tools

### PR DESCRIPTION
**Pull request by sleepyghost-zzz**
Added 58 Javadocs for vision and parameter tools. They have detailed descriptions about they class and methods and link to other code snippets.

### CODE REVIEW

**Comment by linglejack06** [comment]
@sleepyghost-zzz i actually just rewrote vision :( but i went ahead and added a lot of comments explaining the methods within code. Most of the methods are similar, so descriptions should be able to be copied over. But if you need to work on other javadocs i can add them to the vision here. @jkleiber what would you prefer?

**Comment by sleepyghost-zzz** [comment]
@linglejack06 rip. I was told to work on parameter tools and vision javadocs and @Samson560915 would work on the other ones. We'll see what @jkleiber wants, i am fine with rewriting the vision stuff if need be. If you have written comments a lot of the descriptions can probably just be adjusted to fit what the method is doing.

**Comment by jkleiber** [comment]
@sleepyghost-zzz @linglejack06 let's just merge the javadoc updates and have Jack update the docs as needed

**Review by jkleiber — APPROVED** [review]
Approved

**Pull request merged**
