### PR TITLE
Update coppercore to 2025

### PR DESCRIPTION
**Pull request by aidnem**
Changes:
- Change all build.gradles that reference advantagekit or wpilib versions to use variables.
- Update wpilib to 2025.1.1-beta-1
- Update advantagekit to 4.0.0-alpha-1
- Change coppercore vision to 2025.0.0-beta

### CODE REVIEW

**Comment by aidnem** [comment]
@jkleiber What would you prefer that I version this code as? The ideas I have in mind are 2025.0.0-beta, or 2024.12.5-beta, although I find the 2024 to be slightly misleading since it's now using 2025 code.

**Comment by jkleiber** [comment]
I prefer 2025.0.0-beta since it is clearly 2025 and a prerelease

**Review by jkleiber — APPROVED** [review]

**Comment by jkleiber** [comment]
@aidnem after you merge this, create a release on github to automatically add the new version to maven central

We can always release to the same version twice if we want (this is not great practice but we're still early enough into development that it's fine imo)

**Comment by aidnem** [comment]
@jkleiber would you mind taking a look at the draft release to make sure everything is okay? I've never made a release before.

**Comment by jkleiber** [comment]
@aidnem LGTM

**Comment by aidnem** [comment]
Thanks, release published now.

**Comment by aidnem** [comment]
@jkleiber should the action automatically run to publish or do I have to run it myself?

**Comment by jkleiber** [comment]
@aidnem it _should_ run automatically but it looks like it didn't. I might have broken the workflow when I was fixing maven publishing in general. For this one try running it manually

**Comment by aidnem** [comment]
Okay, I ran it and it [looks like it's published now](https://central.sonatype.com/artifact/io.github.team401.coppercore/math/versions). I'll try importing and using it tomorrow.

**Pull request merged**
